[package]
name = "rust-hello"
version = "0.1.0"
authors = ["lhh <776334655@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"
linked-list = "0.0.3"
regex = "1.0.5"