[package]
name = "e_mysql"
version = "0.1.0"
authors = ["livo <1197829331@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["mysql"] }
dotenv = "0.9.0"
