[package]
name = "a_11_web"
version = "0.1.0"
authors = ["Administrator <1197829331@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "*"
rustc-serialize = "0.3.18"
